- alias: 911_mqtt_lost
  initial_state: true
  trigger:
   platform: state
   entity_id: sensor.mqtt_state
   to: 'unavailable'
  condition:
    - condition: state
      entity_id: switch.control_mode
      state: 'on'
  action:
    - service: telegram_bot.send_message
      data_template:
        target:
            - !secret chat_id_group_tech
        message: | 
             Ужасные новости
             Дон Хуан покинул нас в {{ states('sensor.time_date') }}

- alias: 911_mqtt_online
  initial_state: true
  trigger:
   platform: state
   entity_id: sensor.mqtt_state
   from: 'unavailable'
  condition:
   - condition: state
     entity_id: switch.control_mode
     state: 'on'
  action:
    - service: telegram_bot.send_message
      data_template:
        target:
            - !secret chat_id_group_tech
        message: | 
             Как луч света в темноте
             Дон Хуан вернулся к нам в {{ states('sensor.time_date') }}
        
- alias: 911_test_lost
  initial_state: true
  trigger:
   platform: state
   entity_id: sensor.test_state
   to: 'unavailable'
  condition:
   - condition: state
     entity_id: switch.control_mode
     state: 'on'
  action:
    - service: telegram_bot.send_message
      data_template:
        target:
            - !secret chat_id_group_tech
        message: | 
             Мы потеряли тестовый сервер, не нарочно, прасцице {{ states('sensor.time_date') }}

- alias: 911_test_online
  initial_state: true
  trigger:
   platform: state
   entity_id: sensor.test_state
   from: 'unavailable'
  condition:
   - condition: state
     entity_id: switch.control_mode
     state: 'on'
  action:
    - service: telegram_bot.send_message
      data_template:
        target:
            - !secret chat_id_group_tech
        message: | 
             О, мы снова нашли тестовый сервер, он лежал под тумбочкой {{ states('sensor.time_date') }}